# fly.toml app configuration file generated for bettercv on 2026-03-29T17:46:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bettercv'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEBUG = 'False'
  ENV = "production"
  PORT = '8000'
  ALLOWED_HOSTS = ".fly.dev,bettercv.xyz,www.bettercv.xyz"
  DATABASE_PATH = "/data/db.sqlite3"
  DJANGO_SETTINGS_MODULE = "ats_analyzer.settings.production"

[mounts]
  source = "bettercv_data"
  destination = "/data"

[processes]
  app = "./entrypoint.sh"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    path = "/"


[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
