"""
Django settings for ats_analyzer project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from logging import config as logging_config
from pathlib import Path

import environ
import sentry_sdk

from .logging import LOGGING


BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env(
    DEBUG=(bool, True),
    ENV=(str, "dev"),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
)
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG")

ENV = env("ENV")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.accounts',
    'apps.analyzer',
    'apps.coach',
    'apps.compare',
    'apps.home',
    'apps.writer',
]

ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY")

SENTRY_DSN = env("SENTRY_DSN", default="")

if SENTRY_DSN and ENV == "production":
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=ENV,
        traces_sample_rate=0.0,
        send_default_pii=False,
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ats_analyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.shared.context_processors.analytics',
            ],
        },
    },
]

WSGI_APPLICATION = 'ats_analyzer.wsgi.application'

# Logging
LOGGING_CONFIG = None  # Needed to use `logging.config.dictConfig` manually
logging_config.dictConfig(LOGGING)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': env("DATABASE_PATH", default=BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = [BASE_DIR / "common_static"]

MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = env("MEDIA_ROOT", default=BASE_DIR / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Authentication ───────────────────────────────────────────────────────────

AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.EmailBackend',
    'sesame.backends.ModelBackend',
    'django.contrib.auth.backends.ModelBackend',  # keeps /admin/ login working
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'

SESAME_MAX_AGE = 900  # 15-minute magic links
SESAME_ONE_TIME = True  # Invalidate token after first use

# ── Lemon Squeezy ────────────────────────────────────────────────────────────

LEMON_SQUEEZY_WEBHOOK_SECRET = env('LEMON_SQUEEZY_WEBHOOK_SECRET', default='change-me')

CREDIT_PACKAGES = [
    {
        'id': 'starter',
        'label': 'Starter',
        'credits': 20,
        'price_usd': 5,
        'variant_id': env('LS_VARIANT_STARTER', default=''),
        'product_id': env('LS_PRODUCT_STARTER', default=''),
    },
    {
        'id': 'standard',
        'label': 'Standard',
        'credits': 50,
        'price_usd': 10,
        'variant_id': env('LS_VARIANT_STANDARD', default=''),
        'product_id': env('LS_PRODUCT_STANDARD', default=''),
    },
    {
        'id': 'pro',
        'label': 'Pro',
        'credits': 120,
        'price_usd': 20,
        'variant_id': env('LS_VARIANT_PRO', default=''),
        'product_id': env('LS_PRODUCT_PRO', default=''),
    },
]

